/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_brickbit_gsm_GSMUtil */

#ifndef _Included_be_brickbit_gsm_GSMUtil
#define _Included_be_brickbit_gsm_GSMUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_brickbit_gsm_GSMUtil
 * Method:    initGSM
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_brickbit_gsm_GSMUtil_initGSM
  (JNIEnv *, jclass);

/*
 * Class:     be_brickbit_gsm_GSMUtil
 * Method:    readSMS
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_be_brickbit_gsm_GSMUtil_readSMS
  (JNIEnv *, jclass);

/*
 * Class:     be_brickbit_gsm_GSMUtil
 * Method:    sendSMS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_be_brickbit_gsm_GSMUtil_sendSMS
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
